[workspace]
resolver = "2"
members = [
    "detection",
    "movement",
    "simulation",
]

[workspace.dependencies]
mujoco-rs = { version = "5.0", features = ["auto-download-mujoco"] }
nalgebra = "0.33"
serde = "1.0.229"
serde_json = "1.0.151"
opencv-rs = "0.1.2"
image = "0.25.10"
vstd = "0.0.0-2026-08-23-0033"

